version: "3"

services:
  database:
    image: bitnami/postgresql:latest
    container_name: tractian-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tractian
      - POSTGRES_PASSWORD=tractian
      - POSTGRES_DB=tractian
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: tractian
    restart: always
    ports:
      - 3333:3333
      - 9000:9000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
